flags: {}
nix:
  packages:
  - zlib
  enable: false
user-message: ! 'Warning: Specified resolver could not satisfy all dependencies. Some
  external packages have been added as dependencies.

  You can suppress this message by removing it from stack.yaml

'
extra-package-dbs: []
packages:
- .
- ekg-elasticsearch-examples
resolver: lts-14.27
